name: Build and Push Docker image

on:
  push:
    branches: [ main ]

env:
  DOCKER_HUB_REPOSITORY: meryamm/weatherapp
  DOCKER_IMAGE_TAG: v1.2

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build ./api -t ${{ env.DOCKER_HUB_REPOSITORY }}:latest \
                             -t ${{ env.DOCKER_HUB_REPOSITORY }}:${{ env.DOCKER_IMAGE_TAG }} \
                             -t ${{ env.DOCKER_HUB_REPOSITORY }}:${{ github.sha }}
          docker push ${{ env.DOCKER_HUB_REPOSITORY }}:latest
          docker push ${{ env.DOCKER_HUB_REPOSITORY }}:${{ env.DOCKER_IMAGE_TAG }}
          docker push ${{ env.DOCKER_HUB_REPOSITORY }}:${{ github.sha }}

      - name: Logout from Docker Hub
        run: docker logout